apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: meeting-room-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - {{ .Values.global.domain }}
    secretName: meeting-room-tls
  rules:
  - host: {{ .Values.global.domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.nginx.name }}
            port:
              number: {{ .Values.nginx.port }}